name: Build and Deploy Code
on: 
  push:
    branches: 
      - "main"
      - "anotherbranch"
  pull_request:
    branches:
      - "test_branch"

jobs:
  job1: 
    runs-on: ubuntu-latest
    steps: 
      - name: pulling git repo
        uses: actions/checkout@v2 
      - name: Say Hi
        run: echo "Hello YF"
        

